/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface QuoteData {
  /**
   * Ticker or identifier
   */
  ticker: string;
  /**
   * Name of asset
   */
  name: string;
  /**
   * Name of asset's market
   */
  market?: string;
  /**
   * Current price
   */
  price: number;
  /**
   * Price change from previous
   */
  change: number;
  /**
   * Price change from previous
   */
  changePercent?: number;
}
