name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn

    - name: Build 
      run: yarn build

    - name: Build Docs
      run: yarn docs

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn tests
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload test results
      uses: actions/upload-artifact@v5
      with:
        name: jest-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: packages/core/junit.xml
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
            **/junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload coverage
      uses: codecov/codecov-action@v5

    - name: Deploy Documentatinoj
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/
        force_orphan: true
